select
    "Rndrng_NPI" as rendering_npi,
    "Rndrng_Prvdr_Last_Org_Name" as rendering_provider_last_org_name,
    "Rndrng_Prvdr_First_Name" as rendering_provider_first_name,
    "Rndrng_Prvdr_MI" as rendering_provider_middle_initial,
    "Rndrng_Prvdr_Crdntls" as rendering_provider_credentials,
    "Rndrng_Prvdr_St1" as rendering_provider_street_1,
    "Rndrng_Prvdr_St2" as rendering_provider_street_2,
    "Rndrng_Prvdr_City" as rendering_provider_city,
    "Rndrng_Prvdr_State_Abrvtn" as state_code,
    "Rndrng_Prvdr_State_FIPS" as state_fips,
    "Rndrng_Prvdr_Zip5" as zip_code,
    "Rndrng_Prvdr_RUCA" as ruca_code,
    "Rndrng_Prvdr_RUCA_Desc" as ruca_description,
    "Rndrng_Prvdr_Cntry" as country_code,
    "Rndrng_Prvdr_Type" as provider_type,
    "Rndrng_Prvdr_Mdcr_Prtcptg_Ind" as medicare_participation_indicator,
    "Tot_Benes" as total_beneficiaries,
    "Tot_Srvcs" as total_services,
    "Tot_Mdcr_Alowd_Amt" as total_medicare_allowed_amount,
    "Tot_Mdcr_Pymt_Amt" as total_medicare_payment_amount,
    "Bene_Avg_Age" as beneficiary_avg_age,
    "Bene_Avg_Risk_Scre" as beneficiary_avg_risk_score
from {{ source('healthcare_raw', 'RAW_PHYSICIANS') }}