select
    "Facility ID" as facility_id,
    "Facility Name" as facility_name,
    "Address" as address,
    "City/Town" as city,
    "State" as state_code,
    "ZIP Code" as zip_code,
    "County/Parish" as county,
    "Telephone Number" as telephone_number,
    "HCAHPS Measure ID" as hcahps_measure_id,
    "HCAHPS Question" as hcahps_question,
    "HCAHPS Answer Description" as hcahps_answer_description,
    "Patient Survey Star Rating" as patient_survey_star_rating,
    "Patient Survey Star Rating Footnote" as patient_survey_star_rating_footnote,
    "HCAHPS Answer Percent" as hcahps_answer_percent,
    "HCAHPS Answer Percent Footnote" as hcahps_answer_percent_footnote,
    "HCAHPS Linear Mean Value" as hcahps_linear_mean_value,
    "Number of Completed Surveys" as number_of_completed_surveys,
    "Number of Completed Surveys Footnote" as number_of_completed_surveys_footnote,
    "Survey Response Rate Percent" as survey_response_rate_percent,
    "Survey Response Rate Percent Footnote" as survey_response_rate_percent_footnote,
    "Start Date" as start_date,
    "End Date" as end_date
from {{ source('healthcare_raw', 'RAW_HCAHPS') }}